<div class="flex1">
  <h2>ADD CATEGORY</h2>
  <form method="post"  enctype="multipart/form-data" class="flex1">
    <label for="category-name">category-name</label><input type="text" name="category-name" value="">
    <label for="category_description">category_description</label><input type="text" name="category_description" value="">
    <button type="submit" name="category" value="category" >valider</button>
  </form>
</div>
<br>
<div class="flex1">
<?php if(isset($name)){ var_dump($name); }?>
  <h2>CHANGE CATEGORY</h2>
  <form method="get"  enctype="multipart/form-data" class="flex1">
    <label for="category-name">category-name</label><input type="text" name="category-name" value="">
    <button type="input"   value="change_choosen_category">modifier</button>
  </form>
  <br>
  <form method="post"  id="form_modif" enctype="multipart/form-data" class="flex1">
    <label for="category-name">category-name</label>
    <input type="text" name="category-name" value="" placeholder="<?php if(isset($name)){ echo $name['category_name']; } ?>" >
    <label for="category_description">category_description</label><input type="text" name="category_description" value="" placeholder="<?php if(isset($name)){ echo $name['category_description']; } ?>">
    <button type="submit" name="category" value="validate_choosen_category" >valider</button>
  </form>
</div>

<div class="flex1">

  <h2>ERASE CATEGORY</h2>
  <form method="post"  enctype="multipart/form-data" class="flex1">
    <label for="category-name">category-name</label>
    <input type="text" name="category-name" value="">
    <button type="submit" name="erase_category" value="erase_category">effacer</button>
  </form>
</div>
