<h1>INSCRIPTION</h1>
<form method="post"  enctype="multipart/form-data">
  <label for="first_name">first_name</label><input type="text" name="first_name" value="">
  <label for="last_name">last_name</label><input type="text" name="last_name" value="">
  <label for="email">email</label><input type="email" name="email" value=""><br>
  <label for="password">PASSWORD</label>
  <input type="text" name="password" >
  <label for="street">street</label>
  <input type="text" name="street" >
  <label for="city">city</label>
  <input type="text" name="city">
  <label for="code_postal">code_postal</label>
  <input type="text" name="code_postal">
  <label for="tel">tel</label>
  <input type="text" name="tel">
  <button type="submit" >valider</button>

</form>
